### ISSUE TITLE
Why trim-leading() before return?

### ISSUE THREAD

**Issue by CurtTilmes** [jkramer/p6-Text-Wrap#4]
If I want to wrap my paragraph, indenting the whole thing by 10 spaces, I call wrap-text($mytext, :prefix(' ' x 10)), but it removes my specified prefix from the beginning of the first line?

Personally, I would just remove that call -- if someone wants trim-leading(), they can just trim the return, but  otherwise, you could make it optional.

For now I'll just tack my prefix back on the beginning after it gets trimmed off.

In any event, if you keep the default to trim-leading, should add that to the docs.

**Comment by jkramer** [comment]
The `trim-leading` was needed to remove leading line breaks that were added under some circumstances when using `:hard-wrap`, I didn't consider intentionally added spaces using `;prefix`. The last version should fix that problem.

5db8c02d3d88ee26ba11ce1a1165420b32e90b7f
