### ISSUE TITLE
Fails when used by other modules

### ISSUE THREAD

**Issue by tbrowder** [jkramer/p6-Text-Wrap#8]
In particular, this results in a failure:

    zef install GraphQL

The error is caused by the using programs expecting an entry like this in your META6.json file:

    “auth”: “github:jkramer”,

The zef installer does **not** use the “author” field for module ownership. I will submit a PR shortly that should fix the problem

**Comment by tbrowder** [comment]
See PR #9 which should fix the issue.

**Comment by jkramer** [comment]
Thank you for the fix, I just merged your PR.
